[workspace]
authors = ["Prottasha Dcruze <claradcruze@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "nfc-pipelines"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nf-core = ">=3.4.1,<4"
nextflow = ">=25.10.0,<26"
singularity = ">=3.8.6,<4"
